### ISSUE TITLE
Feature Request: Non-text Contrast simulation

### ISSUE THREAD

**Issue by bruskowski** [stark-contrast/stark-sketch-plugin#31]
WCAG 2.1. introduced 'Non-text Contrast' as a Success Criterion. It applies to custom designs for controls. These controls often consist of a variety of elements. The guideline states
"[…] visual information required to identify user interface components and states […]" need to achieve at least a 3:1 contrast ratio for the success criterion to be met.
( https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html )

We just learned that a helpful way to quickly figure out whether a design meets this criterion is to get rid of all the parts with contrast below the 3:1 ratio and check whether the remaining parts are sufficient to let users see and understand the control, it's state and purpose.

While this is for sure not bullet-proof, I think it might be helpful tool for people working on more inclusive designs. I'd love to see something like this to be available as a feature of Stark. (Love this plugin btw., so helpful!)

For illustrative purposes, here's a quick and dirty simulation made with two layers in Sketch:
![image](https://user-images.githubusercontent.com/15381942/52434989-f320e080-2b10-11e9-9825-79f0e6a26ab7.png)

[non-text-contrast.sketch.zip](https://github.com/stark-contrast/stark-sketch-plugin/files/2842258/non-text-contrast.sketch.zip)

**Comment by leahprin** [comment]
I love this! +1 for me. 

@richardbruskowski do you know what level of low contrast sensitivity this simulates?

**Comment by richardbruskowski** [comment]
@leahprin 
I would not know how to actually simulate low contrast sensitivity, I just tried to get close to make everything vanish below the 3:1 contrast threshold as defined by the Non-Text Contrast Guidelines. So everything that is still technically visible – even if barely visible – should _roughly_ comply with the success criterion. But it's really just an approximation, to be more precise we'd need to calculate the relative luminance (see https://www.w3.org/TR/2008/REC-WCAG20-20081211/#relativeluminancedef ), I'd assume that's not possible with just layer blend modes in Sketch.

**Comment by leahprin** [comment]
Cool, good to know @richardbruskowski. 

How would I do the same thing for regular sized text (16px)?

**Comment by richardbruskowski** [comment]
@leahprin 
You could adjust the opacity of the layer. But actually I think it is easier and it definitely is more precise to just compare text and background colours. For Non-Text Contrast, it can be somewhat effortful to do, though, when a graphic or control consists of a plenitude of colours and shades, shadows and gradients, overlapping each other.
