### ISSUE TITLE
Feature Request: Old colorblind simulation style

### ISSUE THREAD

**Issue by saskiae** [stark-contrast/stark-sketch-plugin#32]
Edit: Forgot to say that I love this tool and use it pretty much everyday!

I frequently used the old version to quickly compare color options in the colorblind simulator across multiple artboards. I am unable to do this now with the new design, it's impossible to quickly compare two artboard options as the simulation type resets when I change artboards but even if it kept the simulation type, I would find it much harder to compare by swapping vs side by side. I find the tool much less valuable because of the update. Would it be possible to add the option to use the old colorblind simulation?

**Comment by dube1503** [comment]
Would also like to see the old colorblind simulation comeback for some additional reasons:
 - With the new mode, the colorblind simulation appears inside a _**boxed display within a fixed size window**_ meaning I cannot see the artboard I am testing at its actual full size without setting the zoom and dragging, making a much more tedious process
 - The new colorblind mode now requires you to select a single artboard which, as stated by @saskiae, limits quickly checking colorblind across multiple artboards, but it also means _**there is no support for simulating on symbols**_ which may sound like a minor inconvenience however it adds a large amount of added steps of placing each symbol on an artboard on top of the new steps of switching between every artboard in the windowed simulation, which is very tedious with several symbols.
