### ISSUE TITLE
Request: indicators of most common color blindness types

### ISSUE THREAD

**Issue by gordo** [stark-contrast/stark-sketch-plugin#7]
Love the color blindness feature preview! I've noticed some other color blindness preview tools indicate which color blindness types are the most common in the selector (Deuteranomaly (6% of males), Protanomaly (1%), Deuteranopia (1%), Protanopia (1%)).

Though I usually see it marked qualitatively in other apps ("Common", "Rare", "Very Rare").

I thought something in this vein might be useful for those who are less familiar with the different types.

**Comment by mfouquet** [comment]
Agree 100% - we're thinking through the best ways to add in more info like this. Thanks for suggesting!
