### ISSUE TITLE
Easy way to toggle through all color modes

### ISSUE THREAD

**Issue by lukasoppermann** [stark-contrast/stark-sketch-plugin#8]
Hey, pretty fantastic plugin! 👍 

it would be pretty if you could add shortcut to go to the next / previous color blindness mode. This would make it easy to toggle through them quickly to check where you have issues.

Thanks.

**Comment by mfouquet** [comment]
Definitely something we can do. Will try to get this added in the next release.

**Comment by lukasoppermann** [comment]
That would be very awesome. I am really happy that accessibility tools are coming to sketch. Very nice work. 👍
